version: '3.5'

services:
  go_monday:
    restart: on-failure
    image: postgres:11
    ports:
    - 5432:5432
    volumes:
      - ./db/db-data:/var/lib/postgresql/data/pgdata
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--data-checksums"
    user: "${HOST_UID}:${HOST_GID}"
  redis:
    restart: on-failure
    image: 'bitnami/redis:latest'
    container_name: monday_cache
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PREFIX=${REDIS_PREFIX}
    ports:
    - 6379:6379
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
volumes:
  go_monday:
  postgres-data:
